package com.ariadnext.idcheckio

internal const val ACTIVATE = "activate"
internal const val START = "start"
internal const val START_ONLINE = "startOnline"
internal const val ANALYZE = "analyze"

internal const val LICENSE = "license"
internal const val DISABLE_AUDIO = "disableAudioForLiveness"
internal const val ENVIRONMENT = "environment"
internal const val EXTRACT_DATA = "extractData"
internal const val PARAMS = "params"
internal const val IS_ONLINE = "isOnline"
internal const val ONLINE_CONTEXT = "onlineContext"
internal const val SIDE_1_URI = "side1Uri"
internal const val SIDE_2_URI = "side1Uri"

internal const val DOCUMENT_TYPE = "DocumentType"
internal const val CONFIRM_TYPE = "ConfirmType"
internal const val SIDE_1_EXTRACTION = "Side1Extraction"
internal const val SIDE_2_EXTRACTION = "Side2Extraction"
internal const val DATA_REQUIREMENT = "DataRequirement"
internal const val FACE_DETECTION = "FaceDetection"
internal const val SCAN_BOTH_SIDES = "ScanBothSides"
internal const val USE_HD = "UseHd"
internal const val INTEGRITY_CHECK = "IntegrityCheck"
internal const val READ_EMRTD = "ReadEmrtd"
internal const val ORIENTATION = "Orientation"

internal const val ONLINE_CONFIG = "OnlineConfig"
internal const val IS_REFERENCE_DOC = "isReferenceDocument"
internal const val CHECK_TYPE = "checkType"
internal const val CIS_TYPE = "cisType"
internal const val FOLDER_UID = "folderUid"
internal const val BIOMETRIC_CONSENT = "biometricConsent"
internal const val ENABLE_MANUAL_ANALYSIS = "enableManualAnalysis"

internal const val LANGUAGE = "Language"
internal const val MANUAL_BUTTON_TIMER = "ManualButtonTimer"
internal const val MAX_PICTURE_FILESIZE = "MaxPictureFilesize"
internal const val FEEDBACK_LEVEL = "FeedbackLevel"
internal const val TOKEN = "Token"
internal const val ADJUST_CROP = "AdjustCrop"
internal const val CONFIRM_ABORT = "ConfirmAbort"

internal const val REFERENCE_DOC_UID = "referenceDocUid"
internal const val REFERENCE_TASK_UID = "referenceTaskUid"
internal const val TASK_UID = "taskUid"
internal const val DOCUMENT_UID = "documentUid"
internal const val LIVENESS_STATUS = "livenessStatus"
internal const val ATTACHMENT_TASK_UIDS = "attachmentTaskUids"
internal const val ATTACHMENT_DOCUMENT_UIDS = "attachmentDocumentUids"
